# Generated by Django 3.1.4 on 2021-01-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='s_type',
            field=models.IntegerField(default=1),
        ),
    ]
