# Generated by Django 3.1.4 on 2021-01-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_app', '0002_tasks_s_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='s_type',
            field=models.CharField(default='undone', max_length=20),
        ),
    ]
